import {
  Stethoscope,
  HeartPulse,
  Sparkles,
  PawPrint,
  Activity,
  Scale,
  Calculator,
  ShieldCheck,
  Home,
  Landmark,
  UtensilsCrossed,
  Hotel,
  Scissors,
  Dumbbell,
  HardHat,
  Wind,
  Wrench,
  Zap,
  Hammer,
  Trees,
  Sparkle,
  Bug,
  Car,
  CarFront,
  Truck,
  ShoppingBag,
  Gem,
  Sofa,
  Pill,
  Baby,
  GraduationCap,
  PartyPopper,
  Heart,
  Camera,
  Boxes,
  Warehouse,
  Building2,
  ClipboardCheck,
  Lock,
  Server,
  Megaphone,
  MapPin,
  Search,
  BarChart3,
  Star,
  Compass,
  Layers,
  Cpu,
  type LucideIcon,
} from "lucide-react";

export type Industry = { name: string; icon: LucideIcon; blurb: string; group: string };

export const industries: Industry[] = [
  { name: "Dentists & Dental Clinics", icon: Stethoscope, group: "Medical", blurb: "New-patient acquisition through Maps, reviews, and neighborhood-level intent." },
  { name: "Doctors & Medical Practices", icon: HeartPulse, group: "Medical", blurb: "Trust-first Local SEO for family, specialist, and urgent care practices." },
  { name: "Plastic Surgeons & Cosmetic Clinics", icon: Sparkles, group: "Medical", blurb: "High-intent, high-value keyword strategy with reputation depth." },
  { name: "Veterinarians & Animal Hospitals", icon: PawPrint, group: "Medical", blurb: "Community-driven visibility and review programs pet owners actually read." },
  { name: "Chiropractors & Physiotherapists", icon: Activity, group: "Medical", blurb: "Service-radius targeting with condition- and technique-specific keywords." },
  { name: "Law Firms & Attorneys", icon: Scale, group: "Professional", blurb: "Compete for premium local keywords with authority-grade content and citations." },
  { name: "Accountants & Tax Professionals", icon: Calculator, group: "Professional", blurb: "Seasonal-intent aware campaigns for CPA, tax prep, and advisory firms." },
  { name: "Financial Advisors & Insurance Agencies", icon: ShieldCheck, group: "Professional", blurb: "Trust-signal-heavy Local SEO built for regulated categories." },
  { name: "Real Estate Agents & Brokerages", icon: Home, group: "Professional", blurb: "Neighborhood-level ranking and Google Business Profile authority." },
  { name: "Mortgage Brokers", icon: Landmark, group: "Professional", blurb: "Rate-sensitive local intent captured across service areas." },
  { name: "Restaurants & Cafés", icon: UtensilsCrossed, group: "Hospitality", blurb: "Directions, photos, and reviews — the levers that fill tables." },
  { name: "Hotels, Resorts & Vacation Rentals", icon: Hotel, group: "Hospitality", blurb: "Destination and micro-market visibility for direct bookings." },
  { name: "Salons, Spas & Barbershops", icon: Scissors, group: "Personal", blurb: "Style-specific keywords and hyperlocal booking intent." },
  { name: "Gyms, Yoga Studios & Fitness Centers", icon: Dumbbell, group: "Personal", blurb: "Neighborhood-first campaigns for classes, memberships, and trials." },
  { name: "Contractors & Construction Companies", icon: HardHat, group: "Home Services", blurb: "Service-area SEO for GCs, remodelers, and specialty trades." },
  { name: "HVAC Companies", icon: Wind, group: "Home Services", blurb: "Emergency-intent Local SEO across seasonal demand curves." },
  { name: "Plumbing Companies", icon: Wrench, group: "Home Services", blurb: "24/7 service-area visibility built for lead-generation." },
  { name: "Electricians", icon: Zap, group: "Home Services", blurb: "Residential and commercial local search built around trade specialties." },
  { name: "Roofing Companies", icon: Hammer, group: "Home Services", blurb: "Storm-response and service-area campaigns tuned for high-ticket jobs." },
  { name: "Landscaping & Lawn Care", icon: Trees, group: "Home Services", blurb: "Seasonal local intent with neighborhood-level targeting." },
  { name: "Cleaning Services", icon: Sparkle, group: "Home Services", blurb: "Recurring-service Local SEO for residential and commercial." },
  { name: "Pest Control Companies", icon: Bug, group: "Home Services", blurb: "Pest-specific keywords across service radius and seasonality." },
  { name: "Auto Repair Shops & Mechanics", icon: Car, group: "Automotive", blurb: "Trust and proximity — the two things drivers search for." },
  { name: "Car Dealerships", icon: CarFront, group: "Automotive", blurb: "Inventory-aware Local SEO for new, used, and service departments." },
  { name: "Towing Companies", icon: Truck, group: "Automotive", blurb: "Immediate-intent visibility across the entire service radius." },
  { name: "Retail Stores & Boutiques", icon: ShoppingBag, group: "Retail", blurb: "Foot-traffic driven Local SEO with product-aware search." },
  { name: "Jewelers", icon: Gem, group: "Retail", blurb: "High-consideration purchases won through trust and local authority." },
  { name: "Furniture Stores", icon: Sofa, group: "Retail", blurb: "Showroom visibility across broader metro service areas." },
  { name: "Pharmacies", icon: Pill, group: "Retail", blurb: "Neighborhood convenience and specialty-service visibility." },
  { name: "Childcare Centers & Daycares", icon: Baby, group: "Education", blurb: "Trust-heavy Local SEO for parents researching close to home." },
  { name: "Schools & Educational Institutions", icon: GraduationCap, group: "Education", blurb: "Enrollment-focused campaigns across catchment areas." },
  { name: "Event Venues", icon: PartyPopper, group: "Events", blurb: "Occasion-specific intent tuned for weddings, corporate, and social." },
  { name: "Wedding Services", icon: Heart, group: "Events", blurb: "High-consideration category with review-driven decisions." },
  { name: "Photographers & Videographers", icon: Camera, group: "Events", blurb: "Portfolio-first Local SEO with style- and occasion-based keywords." },
  { name: "Moving Companies", icon: Boxes, group: "Logistics", blurb: "Origin/destination Local SEO for local and long-distance moves." },
  { name: "Storage Facilities", icon: Warehouse, group: "Logistics", blurb: "Radius-based visibility and unit-type-aware campaigns." },
  { name: "Property Management Companies", icon: Building2, group: "Real Estate", blurb: "Owner-acquisition and tenant-facing Local SEO across markets." },
  { name: "Home Inspection Services", icon: ClipboardCheck, group: "Real Estate", blurb: "Realtor-referral and homeowner search intent, mapped together." },
  { name: "Security System Providers", icon: Lock, group: "Home Services", blurb: "Residential and commercial security intent by service area." },
  { name: "IT & Managed Service Providers", icon: Server, group: "B2B", blurb: "B2B Local SEO across metros and industry verticals served." },
  { name: "Marketing Agencies (White-Label)", icon: Megaphone, group: "B2B", blurb: "White-label Local SEO delivery for agency partners." },
];

export const challenges = [
  { icon: UtensilsCrossed, title: "Restaurants", copy: "Live on directions, photos, and review velocity. Ranking matters, but decision-making happens on the profile." },
  { icon: Scale, title: "Law firms", copy: "Compete for the most expensive local keywords in every market — authority, citations, and content depth win." },
  { icon: HeartPulse, title: "Medical practices", copy: "Trust is the ranking factor. Reviews, credentials, and consistent NAP data outperform aggressive tactics." },
  { icon: HardHat, title: "Contractors & trades", copy: "Service-area Local SEO across radius, seasonality, and emergency-vs-planned intent — profiles must adapt." },
  { icon: Building2, title: "Multi-location brands", copy: "Consistency at scale: citations, GBPs, reviews, and reporting standardized across every location." },
  { icon: ShoppingBag, title: "Retail & boutiques", copy: "Foot traffic depends on hyperlocal visibility, product-aware search, and picture-perfect profiles." },
];

export const workflow = [
  { icon: Search, title: "Industry research", copy: "Map how customers actually search in your category." },
  { icon: Compass, title: "Competitor analysis", copy: "Benchmark local rivals across visibility and reviews." },
  { icon: MapPin, title: "GBP audit", copy: "Score profiles against category best practices." },
  { icon: Layers, title: "Keyword opportunity", copy: "Prioritize local intent by revenue potential." },
  { icon: ShieldCheck, title: "Citations & authority", copy: "Fix NAP, build local links, strengthen trust." },
  { icon: BarChart3, title: "Rank monitoring", copy: "Geo-grid tracking across your service area." },
  { icon: Cpu, title: "Continuous optimization", copy: "Software-guided iteration on what's working." },
];

export const industryServices = [
  { icon: MapPin, t: "Google Business Profile Optimization" },
  { icon: Layers, t: "Local Landing Pages" },
  { icon: ShieldCheck, t: "Citation Management" },
  { icon: Search, t: "Local Keyword Research" },
  { icon: Star, t: "Review Growth" },
  { icon: BarChart3, t: "Local Content Strategy" },
  { icon: Cpu, t: "Reporting & Dashboards" },
  { icon: Sparkles, t: "Reputation Management" },
  { icon: Building2, t: "Multi-location SEO" },
];

export const faqs = [
  { q: "Do you work with businesses outside these industries?", a: "Yes. If your customers search locally, we can build a Local SEO campaign for you. These are the categories we serve most often — not a limit." },
  { q: "Do you support businesses with multiple locations?", a: "Absolutely. Multi-location Local SEO — with per-location profiles, citations, and reporting — is a core specialty." },
  { q: "Do franchises need a different strategy?", a: "Yes. Franchise programs balance corporate standards with local franchisee visibility. We coordinate both." },
  { q: "Are service-area businesses eligible?", a: "Yes. Home services, mobile businesses, and multi-radius operators are a large share of our client base." },
  { q: "Can Local SEO campaigns be fully customized?", a: "Every campaign is built around your industry's search behavior, competitive landscape, and business goals — never off a template." },
];
